version: '3.8'

services:
  webapp:
    image: frederickvernemmen/webapp
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://database:27017/dbmongo
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  tests:
    build: .
    depends_on:
      - webapp
    environment:
      - API_URL=http://webapp:3000
    command: yarn test

volumes:
  mongodb-data:
    name: dbmongo
